### ISSUE TITLE
qbserve

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-ux-research#22]
https://qotoqot.com/qbserve
![image](https://user-images.githubusercontent.com/194400/96754592-6c399780-13c9-11eb-89c7-646caab0a68e.png)
![image](https://user-images.githubusercontent.com/194400/96754877-cd616b00-13c9-11eb-8c18-9380e6075d44.png)

Product details is a _modal_ ... 

![image](https://user-images.githubusercontent.com/194400/96754939-e833df80-13c9-11eb-828a-3a3be657b60d.png)
![image](https://user-images.githubusercontent.com/194400/96755203-524c8480-13ca-11eb-90f5-ae06b6972fb0.png)
![image](https://user-images.githubusercontent.com/194400/96755003-06014480-13ca-11eb-8c9f-759b8d6e97e0.png)
![image](https://user-images.githubusercontent.com/194400/96755029-10bbd980-13ca-11eb-8cd0-bd2868c7eca0.png)
![image](https://user-images.githubusercontent.com/194400/96755065-1dd8c880-13ca-11eb-831f-845f09c65476.png)
![image](https://user-images.githubusercontent.com/194400/96755097-29c48a80-13ca-11eb-9648-a4618353b275.png)

Pricing is a _modal_ ... 🙄 

![image](https://user-images.githubusercontent.com/194400/96754761-ac991580-13c9-11eb-9372-ed2c304bf84f.png)

Discovered via [github.com/samhstn/my-config#qbserve](https://github.com/samhstn/my-config/tree/948ab0cf1d322fa385f1057dce9bf9721e628cc2#qbserve)

Alternatives/comparison: https://www.producthunt.com/alternatives/qbserve

Going to try this for the 15 day free trial.

**Comment by nelsonic** [comment]
The app is small:
![image](https://user-images.githubusercontent.com/194400/96756395-f420a100-13cb-11eb-9d0f-9d856cecca66.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/96756512-11ee0600-13cc-11eb-987a-f567166d3271.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/96756657-45c92b80-13cc-11eb-8fdf-3baa7a8d7238.png)
![image](https://user-images.githubusercontent.com/194400/96756689-4f529380-13cc-11eb-8d60-bb1a79f5af38.png)

**Comment by nelsonic** [comment]
Wow ... this is basically a root kit ... 
![image](https://user-images.githubusercontent.com/194400/96756809-8163f580-13cc-11eb-8af4-06b7728d4666.png)

I'm allowing access on my "work" mac (no personal stuff or internet banking etc)

**Comment by nelsonic** [comment]
Of _course_ it wants unrestricted access to my Google Chrome ...
![image](https://user-images.githubusercontent.com/194400/96765764-11f10480-13d2-11eb-95fa-1910eb8414cf.png)

**Comment by nelsonic** [comment]
First day stats: (baring in mind that I only installed the app at **`after`** the "work" day ended ...)
![image](https://user-images.githubusercontent.com/194400/96799640-812f1e80-13fb-11eb-8828-a1a04efa572e.png)

Fascinating how it reaches into **`Slack`** and extracts the Person's name. Clearly I was doing a bit of GraphQL today ... 😉 
I can certainly see _why_ this app appeals to people. I just _wish_ it was Open Source so I could _trust_ it to not be harvesting my data given that it has elevated system privileges ...

**Comment by iteles** [comment]
There _is_ one thing I like about it: how it breaks the productive vs unproductive/neutral time down by hour in a visual way - it's a neat feature that allows you to track patterns of high vs low energy times in your day across days/weeks.

An open source solution would be _way_ better.

**Comment by nelsonic** [comment]
If you're AFK for a certain time period (_inactive on your computer_) when you return, this dialog appears:
![image](https://user-images.githubusercontent.com/194400/96970137-2553bb00-150b-11eb-9915-a0ee0ffe43a2.png)

No option for a "water break" or "bathroom" or "exercise" ... these seem like obvious default activities.
It's possible to add them in:
![image](https://user-images.githubusercontent.com/194400/96970401-8c716f80-150b-11eb-86ec-8d326b025401.png)

**Comment by nelsonic** [comment]
2% more "productive" than yesterday indeed ... 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/194400/97510777-691c4980-197d-11eb-89f3-f1a5dc5bfb9e.png">
